version: "3.9"
services:
  app:
    image: 484907513258.dkr.ecr.eu-north-1.amazonaws.com/docker/nextjs:latest
    depends_on:
      - postgres-container
    ports:
      - 3000:3000
  postgres-container:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=todo
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin-container:
    image: dpage/pgadmin4
    depends_on:
      - postgres-container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
volumes:
  pgdata:
    external: true
